// ------------------------------------------------------------
// Image sanitizer (shared image-upload phase)
//
// ONE centralized processing pipeline used by every image upload
// (generic admin uploads AND leadership portraits):
//
//   upload bytes
//     → size cap (middleware/upload.js, streaming)
//     → sharp decode with hard input-pixel limit (decompression
//       bombs are rejected, never fully processed)
//     → metadata dimension check BEFORE full decode work
//     → auto-rotate (EXIF orientation) + strip metadata
//       (sharp never copies EXIF/GPS to output unless asked)
//     → re-encode to WebP (server-generated, safe bytes)
//     → discard the original upload entirely
//
// Security properties:
//   - Content is validated by DECODING it, not by trusting the
//     browser's filename, extension or Content-Type header.
//   - The stored file is freshly generated by libvips — polyglot
//     payloads hidden in the original bytes do not survive
//     re-encoding (defense in depth, NOT a malware guarantee).
//   - Processing is time-boxed so a pathological image cannot
//     pin the event loop indefinitely.
//
// Error contract: throws Error instances carrying a `code` from
// UPLOAD_ERROR_CODES so controllers can map them to safe 4xx
// responses without leaking library/filesystem details.
// ------------------------------------------------------------

import sharp from 'sharp';

/** Maximum width/height in pixels (per side). */
export const MAX_IMAGE_DIMENSION = 6000;

/** Maximum total pixel count (decompression-bomb bound). 24 MP. */
export const MAX_IMAGE_PIXELS = 24_000_000;

/** Hard cap on a single upload's bytes (must match middleware/upload.js). */
export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024; // 10 MB

/** Re-encoded output format: WebP (safe, modern, well-compressed). */
export const OUTPUT_FORMAT = 'webp';

/** WebP encoder quality — visually transparent for site imagery. */
const WEBP_QUALITY = 82;

/** Hard CPU/time budget for one image pipeline run. */
const PROCESS_TIMEOUT_SECONDS = 20;

/** Machine-readable validation error codes (mapped to safe 4xx). */
export const UPLOAD_ERROR_CODES = Object.freeze({
  NO_FILE: 'IMAGE_NO_FILE',
  INVALID: 'IMAGE_INVALID',
  DIMENSIONS: 'IMAGE_DIMENSIONS',
  TIMEOUT: 'IMAGE_TIMEOUT',
  PROCESSING: 'IMAGE_PROCESSING',
});

/** Build a validation error the controller can map to a safe message. */
function uploadError(code, message) {
  const err = new Error(message);
  err.code = code;
  return err;
}

/**
 * Sanitize + re-encode an uploaded image buffer.
 *
 * @param {Buffer} buffer raw uploaded bytes (already size-capped)
 * @returns {Promise<{ data: Buffer, width: number, height: number, format: 'webp' }>}
 *   freshly generated WebP bytes — never the original upload.
 * @throws Error with `code` from UPLOAD_ERROR_CODES on invalid input.
 */
export async function sanitizeImageToWebp(buffer) {
  if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
    throw uploadError(UPLOAD_ERROR_CODES.NO_FILE, 'No image file was received.');
  }

  let pipeline;
  try {
    pipeline = sharp(buffer, {
      // failOn 'error': abort on corrupt/truncated input structures.
      failOn: 'error',
      // Backstop against decompression bombs: libvips refuses to
      // fully decode images above this pixel count.
      limitInputPixels: MAX_IMAGE_PIXELS,
      // Never auto-load external resources referenced by the file.
      sequentialRead: true,
    });
    pipeline.timeout({ seconds: PROCESS_TIMEOUT_SECONDS });
  } catch {
    // sharp constructor failures mean the container itself is
    // unusable — treat as invalid input either way.
    throw uploadError(UPLOAD_ERROR_CODES.INVALID, 'Uploaded file is not a supported image.');
  }

  // ---- Cheap header read first: reject bad dimensions BEFORE
  // ---- paying for a full decode + re-encode.
  let metadata;
  try {
    metadata = await pipeline.metadata();
  } catch {
    throw uploadError(
      UPLOAD_ERROR_CODES.INVALID,
      'Uploaded file is not a valid JPEG, PNG or WebP image.',
    );
  }

  if (!metadata.width || !metadata.height) {
    throw uploadError(UPLOAD_ERROR_CODES.INVALID, 'Uploaded file is not a valid image.');
  }
  if (
    metadata.width > MAX_IMAGE_DIMENSION
    || metadata.height > MAX_IMAGE_DIMENSION
    || metadata.width * metadata.height > MAX_IMAGE_PIXELS
  ) {
    throw uploadError(
      UPLOAD_ERROR_CODES.DIMENSIONS,
      `Image dimensions exceed the maximum allowed (${MAX_IMAGE_DIMENSION}×${MAX_IMAGE_DIMENSION} pixels).`,
    );
  }

  // ---- Full decode + sanitize + re-encode.
  try {
    const { data, info } = await pipeline
      .rotate() // normalize EXIF orientation; strips EXIF from output
      .webp({ quality: WEBP_QUALITY, effort: 4 })
      .toBuffer({ resolveWithObject: true });

    if (!data || data.length === 0) {
      throw uploadError(UPLOAD_ERROR_CODES.PROCESSING, 'Image processing failed.');
    }
    return {
      data,
      width: info.width,
      height: info.height,
      format: OUTPUT_FORMAT,
    };
  } catch (err) {
    if (err?.code && Object.values(UPLOAD_ERROR_CODES).includes(err.code)) throw err;

    // sharp/libvips timeouts surface as coded errors on the output
    // step; everything else is invalid input or a processing fault.
    const msg = String(err?.message || '');
    if (/timeout|timed out/i.test(msg)) {
      throw uploadError(
        UPLOAD_ERROR_CODES.TIMEOUT,
        'Image processing took too long. Try a smaller or simpler image.',
      );
    }
    if (/input file missing|unsupported image format|corrupt|premature end|Invalid|invalid/i.test(msg)) {
      throw uploadError(
        UPLOAD_ERROR_CODES.INVALID,
        'Uploaded file is not a valid JPEG, PNG or WebP image.',
      );
    }
    // Unexpected library failure — generic safe message, no details.
    throw uploadError(UPLOAD_ERROR_CODES.PROCESSING, 'Image processing failed.');
  }
}
